### ISSUE TITLE
enhance: replace electron with neutralino

### ISSUE THREAD

**Issue by system32uwu** [ceramic-engine/ceramic#118] opened 2023-06-02 22:14 UTC
Hey, just started using ceramic, i noticed the development binary is packaged with electron, you may prefer https://neutralino.js.org/ instead which is lighter and faster.

https://github.com/Elanis/web-to-desktop-framework-comparison#01-empty-app

![image](https://github.com/ceramic-engine/ceramic/assets/29718978/d56c8ddf-434b-43b5-97d4-b2bb066a3a79)

**Comment by jeremyfa** [comment] 2023-06-04 08:38
Thanks for the suggestion,

Although it could be nice to drastically reduce the size of a Ceramic release, it would also be a lot of work because Ceramic local web testing is built around the usage of electron, and taking advantage of what is exposed via node by electron.

I guess it would be possible to port all this to neutralino, but the risk of bringing regressions on the way is very high. I wouldn't know for sure if I wouldn't run against new problems, while I know the current implementation based on electron works just fine.

Even if the size of electron is not ideal, this concern alone is not enough to convince me to put the work of moving to neutralino.

**Closed by jeremyfa** 2023-06-04 08:38 UTC
